name: CI

on: [push, pull_request]

jobs:
  build-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        pip install -r requirements.txt

    - name: Install NSIS
      run: |
        Invoke-WebRequest "https://github.com/vial-kb/vial-deps/releases/download/v1/nsis-3.06.1-setup.exe" -UserAgent "wget" -OutFile nsis-3.06.1-setup.exe
        if ((Get-FileHash nsis-3.06.1-setup.exe -Algorithm sha256).Hash -ne "f60488a676308079bfdf6845dc7114cfd4bbff47b66be4db827b89bb8d7fdc52") { Write-Error 'SHA256 mismatch' }
        Start-Process -FilePath "nsis-3.06.1-setup.exe" -ArgumentList "/S", "/D=C:\Program Files (x86)\NSIS" -NoNewWindow -Wait

    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        fbs freeze
        Compress-Archive -Path "target\Strataman" -DestinationPath strataman-win.zip

    - uses: actions/upload-artifact@v3
      with:
        name: vial-win
        path: vial-win.zip

    - name: Create installer
      run: |
        $env:Path += ";C:\Program Files (x86)\NSIS"
        . .\venv\Scripts\activate.ps1
        fbs installer

    - uses: actions/upload-artifact@v3
      with:
        name: strataman-win-installer
        path: target\StratamanSetup.exe
